- name: LAMP+WP環境構築(AWS環境)
  hosts: wordpress              # wordpressグループに対して実行
  become: yes                   # ユーザ変更を許可
  roles:
    #- yum-update
    - repository
    - swap
    - common
    - apache24
    - php73
    - mariadb55_WP
    - serverspec
    #- wordpress
