- name: コマンドインストール
  yum:
    name: tree
    state: present

# ロケールは英語のままとする
# - name: ロケール設定済みかを確認
#   shell: localectl status | grep LANG=ja_JP.utf8
#   register: locale_check
#   failed_when: locale_check.rc not in [0, 1]
#   changed_when: false

# - name: ロケールの変更
#   shell: localectl set-locale LANG=ja_JP.utf8
#   when: locale_check.rc == 1
